// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://biiptjvpvlwyghftxkdl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJpaXB0anZwdmx3eWdoZnR4a2RsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA1ODM4NjIsImV4cCI6MjA2NjE1OTg2Mn0.9rteufZ1MIxQ0pkJXANmF28inYtPBaodEvBvTxJlY9Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);